# Generated by Django 5.1.5 on 2025-02-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_previous_song_alter_room_current_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='previous_song',
        ),
    ]
