# Generated by Django 5.1.5 on 2025-02-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_current_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_volume',
            new_name='volume',
        ),
    ]
